[all]
k3s-node-0 ansible_host=192.168.1.50
k3s-node-1 ansible_host=192.168.1.51
k3s-node-2 ansible_host=192.168.1.52
k3s-node-3 ansible_host=192.168.1.53

[masters]
k3s-node-0

[workers]
k3s-node-1
k3s-node-2
k3s-node-3
