---
- name: Install kubectl
  get_url:
    url: "{{ kubectl_bin_url }}"
    dest: /usr/local/bin/kubectl
    mode: 0755
  become: true

- name: Install k3s-server service
  copy:
    src: k3s-server.service
    dest: /etc/systemd/system/k3s-server.service
  become: true

- name: Start and enable k3s-server
  systemd:
    name: k3s-server
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Get join token
  command: cat /var/lib/rancher/k3s/server/node-token
  register: found_join_token
  retries: 30
  delay: 5
  until: found_join_token.rc == 0
  become: true

- name: Save join token
  set_fact:
    k3s_join_token: "{{ found_join_token.stdout }}"

